POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Felix",
    "password": "password"
}
###
GET http://localhost:8000/users
###
POST http://localhost:8000/login
Content-Type: application/json

{
    "name": "Felix",
    "password": "password"
}
###
GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmVsaXgiLCJpYXQiOjE3MDA2MDE5MzUsImV4cCI6MTcwMDYwMTk1MH0.HAK4lSJwcoXN6x47fP5Lo5Cpx-b62_wUGSSFjhYdPho
###
POST http://localhost:8000/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmVsaXgiLCJpYXQiOjE3MDA2MDE4MjB9.B77jgF_AVfZ4_Zp39wtQ_vgT3gK7BYIld-cY0HI5-xs"
}
###
DELETE http://localhost:8000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmVsaXgiLCJpYXQiOjE3MDA2MDE4MjB9.B77jgF_AVfZ4_Zp39wtQ_vgT3gK7BYIld-cY0HI5-xs"
}